language: cpp
compiler:
  - gcc
  - clang

before_install:
    - pushd ..
    - wget "https://github.com/cpputest/cpputest.github.io/blob/master/releases/cpputest-3.6.tar.gz?raw=true" -O cpputest.tar.gz
    - tar -xzf cpputest.tar.gz
    - cd cpputest-3.6/
    - ./configure
    - make
    - sudo make install
    - popd

before_script:
    - mkdir build/
    - cd build/
    - cmake ..

script:
    - make
    - ./tests
